app = "deliverybot-curious-meadowlark-9263"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PUPPETEER_HEADLESS = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  DB_PATH = "/data/database.json"
  LOCAL_AUTH_PATH = "/data/.wwebjs_auth"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[mounts]]
  source = "deliverybot_data"
  destination = "/data"
